title: Juliet Maria # your name (or website title) here
logo: "/images/Juliet_round_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Fullstack | AI | ML 
  <br><br>
  Fullstack | AI | ML 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
